### ISSUE TITLE
Can't start a new project right after having installed X-way

### ISSUE THREAD

**Issue by Fen747** [kaviarjs/x-bundle#1]
**Describe the bug**
After installing X-way using `npm install -g --save @kaviar/x`, and executing `x` => `x:project` => type project name => press `enter`, the following error message appears :

```
(node:11978) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat '/usr/local/lib/node_modules/@kaviar/x/templates/project'
    at Object.lstatSync (fs.js:1034:3)
    at FSOperator.sessionCopy (/usr/local/lib/node_modules/@kaviar/x/dist/utils/FSOperator.js:83:39)
    at ProjectWriter.write (/usr/local/lib/node_modules/@kaviar/x/dist/writers/ProjectWriter.js:10:20)
    at CommanderService.run (/usr/local/lib/node_modules/@kaviar/x/node_modules/@kaviar/terminal-bundle/dist/services/CommanderService.js:97:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async CommanderService.inquire (/usr/local/lib/node_modules/@kaviar/x/node_modules/@kaviar/terminal-bundle/dist/services/CommanderService.js:64:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11978) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11978) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
Exactly as detailed above : 
- type `npm install -g --save @kaviar/x`
- type `x`
- select `x:project`
- type project name
- press `enter`

Tried in sudo, just in case, and got the same result anyway.

**Expected behavior**
Expected the project to be created so I could follow doc's next step

**Screenshots**
<img width="1294" alt="Screenshot 2020-12-29 at 18 27 51" src="https://user-images.githubusercontent.com/13072245/103302270-916b0780-4a03-11eb-8e51-79ef437f54c6.png">

**Desktop (please complete the following information):**
 - OS: MacBook pro 2017
 - NPM version : 6.14.8
 - Node version : 14.12.0

**Additional context**
Thank you for this awesome project :)

**Comment by theodorDiaconu** [comment]
@Fen747 thanks for the issue! A new release with more features and stability fixes across all packages will follow. But very curious why it doesn't work for you as this worked without problems. Can you check to ensure what are the contents of "@kaviar/x" inside your /usr/local ?

**Comment by theodorDiaconu** [comment]
Is there any reason you did a "sudo" ?

**Comment by Fen747** [comment]
Hi @theodorDiaconu  ! Hope you're well :)

I did a `sudo` just in order to test whether it had an impact, but it's the same result as without it :)
I uninstalled `x` and re-installed it, but the error is still the same.

I've got no `@kaviar/x` in `/usr/local` at all

<img width="488" alt="Screenshot 2021-01-08 at 10 17 07" src="https://user-images.githubusercontent.com/13072245/103996823-aaf61700-519a-11eb-8601-187c13c3725b.png">

I'm quite desperate to start using Kaviar, as it looks a lot like the tool I was working on, but way better and more mature already :)

Thank you for your time !

**Comment by theodorDiaconu** [comment]
1.0.3 released. Added `templates`. Since mostly testing locally with `npm link` and such I missed the fact the production build actually ignores everything unless specified. Added templates now. Should be good.

**Comment by theodorDiaconu** [comment]
You might also still experience some errors. As I have made some upgrades across every package. New releases comming soon. Working on getting a seed fund for this project as I have HUGE plans.

**Comment by Fen747** [comment]
Hi Theodor,

I'd gladly bring you the help I can, this project sounds a lot like a worthy successor of Meteor (I wonder how they could possibily work together, as Meteor has a lot of usefull things already available thaht would be an absolute killer if combined with Kaviar / XWay, like cordova bundling OOTB, easiest pub/sub in the world (though missing real offline-first support imho) ), and it does have a lot of common functionalities with what I have been doing in my garage regarding bridging GQL and Mongo ;)

I've reinstalled and it finally works ! Thank you a lot for your invovlment Theodor ;)

**Comment by Fen747** [comment]
<img width="172" alt="Screenshot 2021-01-08 at 11 41 16" src="https://user-images.githubusercontent.com/13072245/104006182-6cfef000-51a6-11eb-8faa-18a2be65b86f.png">

It's the best pr0n  of my life ahah !
