### ISSUE TITLE
TypeError: Cannot read property 'collection' of undefined

### ISSUE THREAD

**Issue by Fen747** [kaviarjs/x-bundle#4]
**Describe the bug**
When starting the app with `start:watch` script, the app crash while connecting to mongo

**To Reproduce**
1. Put any valid mongo URI in .env as MONGO_URL
2. Start an app using Kaviar's mongo database service

**Expected behavior**
It should start without throwing :)

**Screenshots**
<img width="858" alt="Screenshot 2021-01-08 at 18 36 48" src="https://user-images.githubusercontent.com/13072245/104046496-7a38d080-51e0-11eb-8489-84ea1fd0e7d4.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Node 14

**Additional context**
The Mongo URI is valid and reacheable (through meteor's MONGO_URL and Studio3T)
When I comment all collections imports, its works. I've logged before and after `this.client` is set in DataService constructor, and the after log is available only if no collection is imported in the project. I didn't touched any collection code, it's all `x:collection` generated

**Comment by theodorDiaconu** [comment]
Can you try now with version 1.1.0 ?
