### ISSUE TITLE
Unknown type "JSON" on startup

### ISSUE THREAD

**Issue by Fen747** [kaviarjs/x-bundle#5]
**Describe the bug**
After having created an empty microservice, the app crashes on startup with the below error.

**To Reproduce**
1. `x`
2. `x:microservice`
3. `yarn compile:watch`
4. In another terminal : `yarn start:watch`

**Expected behavior**
The app shoudl not crash

**Screenshots**
<img width="799" alt="Screenshot 2021-01-08 at 19 36 14" src="https://user-images.githubusercontent.com/13072245/104051671-c720a500-51e8-11eb-81f0-a8e1162b9821.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - node 14

**Additional context**
Absolutely no code has been added to the microservice, even throught X cli cmds

**Comment by theodorDiaconu** [comment]
Done.
