### ISSUE TITLE
name is not defined

### ISSUE THREAD

**Issue by Fen747** [kaviarjs/x-bundle#7]
**Describe the bug**
When calling the `register` GQL method, the document is correctly created, but :
- a `name` field is mandatory (we might want it to be optional)
- even when providing it in the `input` variable, the following error occurs

**To Reproduce**
1. Go to `localhost:4000/graphql`
2. Paste this mutation : 
```
mutation register($input: RegistrationInput!) {
	register(input: $input){
		token
	}
}
```
3. and this variables
```
{
  "input": {
    "name": "username",
    "email": "something@gmail.com",
    "password": "password"
  }
}
```

**Expected behavior**
The token should be succesfully returned

**Screenshots**
<img width="687" alt="Screenshot 2021-01-12 at 14 05 23" src="https://user-images.githubusercontent.com/13072245/104318099-3810d700-54df-11eb-9dc1-fb7b1eb70465.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Node 14

**Comment by theodorDiaconu** [comment]
Updated x-password-bundle to 1.0.1 should work now if you update it.
