### ISSUE TITLE
Precise in docs how to handle account mangement password

### ISSUE THREAD

**Issue by Fen747** [kaviarjs/x-bundle#8]
**Is your feature request related to a problem? Please describe.**
It would be useful for new users to know exactly how to handle the token when login, registering, forgeting / reseting password, etc.

Currently, I guess that we have to pass the token in the authorization Header once logged in (prefixed with Token ? Bearer ?)
But what about Password reset / forget tokens ?

**Describe the solution you'd like**
Add a A2Z example in the docs

**Comment by theodorDiaconu** [comment]
Do you mean this: https://www.kaviarjs.com/docs/package-password-bundle ?

**Comment by Fen747** [comment]
No, I mean purely using the GraphQL methods, from a front-end point of vue :)

My bad ! I gave `/graphql` another look, and saw that I simply wasn't checking the proper project and GQL API ahah !

Sorry Theodor, this issue can be closed :)
